### ISSUE TITLE
Erro E0082 - CNPJ do emitente prestador não encontrado no cadastro CNPJ na data de processamento

### ISSUE THREAD

**Issue by and-vinco** [rscarvalho90/NFS-e-Node.js#1]
Erro ao encaminhar DPS na produção.
E0082 - CNPJ do emitente prestador não encontrado no cadastro CNPJ na data de processamento
URL: https://sefin.nfse.gov.br/sefinnacional/nfse
É um MEI de São Paulo.

Em produção restrita recebo o erro: E4007 - Não foi possível obter o certificado de cliente.

**Comment by rscarvalho90** [comment]
Por se tratar de um erro não relacionado diretamente a este projeto, foi aberto um chamado para verificação por parte do responsável pela API. Este relato permanecerá aberto até a correção do erro na API.

**Comment by and-vinco** [comment]
> Por se tratar de um erro não relacionado diretamente a este projeto, foi aberto um chamado para verificação por parte do responsável pela API. Este relato permanecerá aberto até a correção do erro na API.

Obrigado!
Há algum prazo para análise? Encaminhei essa questão no grupo da NFSe, encaminhei o XML de modo privado para análise e continuo no aguardo. 
É um problema que foi relatado por outros desenvolvedores no grupo.

Obrigado!

**Comment by rscarvalho90** [comment]
De acordo com o Serpro, o problema foi corrigido em 19/09/2023. Favor realizar novamente os testes para verificar.

**Comment by rscarvalho90** [comment]
Como não houve resposta, presumirei que o erro foi resolvido. Caso necessário, favor reabrir a issue.
